### ISSUE TITLE
[Feat:] Add Navbar in below tablet view section

### ISSUE THREAD

**Issue by SrinivasDevolper** [jaibhedia/ChainzRegistry#44]
**Is your feature request related to a problem? Please describe.**
The navbar is not good in below tablet view section

**Describe the solution you'd like**
 Add Navbar in below tablet view section

**Additional context**

**Add this feature in below tablet view section**

![image3](https://github.com/jaibhedia/ChainzRegistry/assets/121508628/77c1a1c6-0c00-46f0-bc1c-ed4bc2967c43)

**I am GSSOC24 Contributor
please assign me, I would like to work on this issue**

**Comment by jaibhedia** [comment]
@SrinivasDevolper You have been assigned this issue, please start working on it.

**Comment by SrinivasDevolper** [comment]
Thanks for assing
