### ISSUE TITLE
Favicon.ico update and change the title of the page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [jaibhedia/ChainzRegistry#49]
**Describe the bug**
![image](https://github.com/jaibhedia/ChainzRegistry/assets/125277258/3732cd3d-6b1f-41c1-9f2c-fe56227bc453)
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
the navbar is not looks good

**Comment by TheMystic07** [comment]
please assign this isssue to me

**Comment by jaibhedia** [comment]
@RamakrushnaBiswal You have been assigned this issue, please start working on it.

**Comment by RamakrushnaBiswal** [comment]
solved with Pr #55
